services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      TZ: Asia/Hong_Kong
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      TZ: Asia/Hong_Kong
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      TZ: "Asia/Hong_Kong"
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3.11.15-management-alpine
    container_name: rabbitmq
    environment:
      TZ: "Asia/Hong_Kong"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

  eureka-server:
    image: cmingfai/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - TZ=Asia/Hong_Kong
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin

  api-gateway:
    image: cmingfai/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8083:8083"
    environment:
      - TZ=Asia/Hong_Kong
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server

  customer:
    image: cmingfai/customer:latest
    container_name: customer
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Hong_Kong
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq

  fraud:
    image: cmingfai/fraud:latest
    container_name: fraud
    ports:
      - "8081:8081"
    environment:
      - TZ=Asia/Hong_Kong
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq

  notification:
    image: cmingfai/notification:latest
    container_name: notification
    ports:
      - "8082:8082"
    environment:
      - TZ=Asia/Hong_Kong
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: