apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  labels:
    app: fraud
spec:
  replicas: 1
  template:
    metadata:
      name: fraud
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: cmingfai/fraud:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_DATASOURCE_USERNAME
              value:
            - name: SPRING_DATASOURCE_PASSWORD
              value:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/fraud
            - name: TZ
              value: Asia/Hong_Kong
      restartPolicy: Always
  selector:
    matchLabels:
      app: fraud
